// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdksFKVarhJ4XZBgYunDdPVrrtQsGRV5k',
    appId: '1:1059145661089:web:3e5d2c2f986ad07dc48ee0',
    messagingSenderId: '1059145661089',
    projectId: 'esaafai',
    authDomain: 'esaafai.firebaseapp.com',
    storageBucket: 'esaafai.firebasestorage.app',
    measurementId: 'G-YKC68K5NXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSTV8R8stF8remcIDtIILotemXDiEbso',
    appId: '1:1059145661089:android:89422f3758629decc48ee0',
    messagingSenderId: '1059145661089',
    projectId: 'esaafai',
    storageBucket: 'esaafai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPQPOPEosaPVpqPUSsbzosvYBbGa6Csg',
    appId: '1:1059145661089:ios:d4183d2a5aa3f532c48ee0',
    messagingSenderId: '1059145661089',
    projectId: 'esaafai',
    storageBucket: 'esaafai.firebasestorage.app',
    iosBundleId: 'com.example.esaafAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYPQPOPEosaPVpqPUSsbzosvYBbGa6Csg',
    appId: '1:1059145661089:ios:d4183d2a5aa3f532c48ee0',
    messagingSenderId: '1059145661089',
    projectId: 'esaafai',
    storageBucket: 'esaafai.firebasestorage.app',
    iosBundleId: 'com.example.esaafAi',
  );
}
